server:
  port: 8086

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:sufwkSCtLCfM2jkLr4nU@containers-us-west-29.railway.app:6082/railway
    username: postgres
    password: sufwkSCtLCfM2jkLr4nU
    pool:
      enabled: true
      initial-size: 1
      max-size: 1

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG